# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4e0c37e26a1e6b300c4be3ca8a2db9e36216ce1171f0c1a117b26b280158402ee824eefaa04dd1abc8404b84d505281d6cc7f3adbd81b97bf79125197c202370

test:
  secret_key_base: 0322078801bf4e7f8f7613581214aa8ff0d670919575ff82a4a284bcf864c9614bc2cc3ac0dafe569a8b5a938372b6da28ec6d992ca332889db4d9753d7518b4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
